--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Users; Type: TABLE; Schema: public; Owner: funduruk
--

CREATE TABLE public."Users" (
);


ALTER TABLE public."Users" OWNER TO funduruk;

--
-- Name: asddsa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.asddsa (
    id bigint NOT NULL,
    active boolean,
    date_of_created timestamp(6) without time zone,
    email character varying(255),
    password character varying(1000),
    phone_number character varying(255),
    username character varying(255)
);


ALTER TABLE public.asddsa OWNER TO postgres;

--
-- Name: asddsa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.asddsa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asddsa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_role (
    user_id bigint NOT NULL,
    roles character varying(255),
    CONSTRAINT user_role_roles_check CHECK (((roles)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_USER'::character varying])::text[])))
);


ALTER TABLE public.user_role OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean,
    date_of_created timestamp(6) without time zone,
    email character varying(255),
    password character varying(1000),
    phone_number character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: funduruk
--

COPY public."Users"  FROM stdin;
\.


--
-- Data for Name: asddsa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.asddsa (id, active, date_of_created, email, password, phone_number, username) FROM stdin;
\.


--
-- Data for Name: user_role; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_role (user_id, roles) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, active, date_of_created, email, password, phone_number, username) FROM stdin;
1	f	2024-10-13 02:51:04.718776	test@example.com	$2a$08$rU9/3cQ3ijgJRtVebSVkr.9f0fp/5y9LYczHgb8KmulZ1owp3IZfG	\N	testuser
4	f	2024-10-14 00:48:23.250618	test1@example.com	$2a$08$XuowJ/WBEWVSvKaihtpECe3kmKnflswlAXPOwB2dIhwOMCfA1j3Ey	\N	testuser1
\.


--
-- Name: asddsa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.asddsa_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- Name: asddsa asddsa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.asddsa
    ADD CONSTRAINT asddsa_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: user_role fk5rsf06lat0i4qmodjc1wfn5w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk5rsf06lat0i4qmodjc1wfn5w FOREIGN KEY (user_id) REFERENCES public.asddsa(id);


--
-- Name: user_role fkj345gk1bovqvfame88rcx7yyx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

